### ISSUE TITLE
这个项目还会更新吗？

### ISSUE THREAD

**Issue by lijinhong11** [KJZH001/Edw-Api-Core#1]

**Comment by KJZH001** [comment]
抱歉，由于我临近高三，现在学业上也确实很忙
关于这个项目，我是有继续更新的打算的，不过出于时间和精力问题，可能会在暑假左右才能有时间进行维护
此外，这个插件当初是为了老版Mirai console编写的，而且存在些许的问题，目前的源代码虽然编译后可以运行，但是我个人并不建议你放在生产环境中使用

**Comment by lijinhong11** [comment]
无回应
